apiVersion: apps/v1
kind: Deployment
metadata:
  name: ws-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ws-server
  template:
    metadata:
      labels:
        app: ws-server
    spec:
      serviceAccountName: ws-server-sa # Give pod necessary permissions
      containers:
        - name: ws-server
          image: balinkrish2000/ws-server:latest
          ports:
            - containerPort: 9000

---

apiVersion: v1
kind: Service
metadata:
  name: ws-service
spec:
  selector:
    app: ws-server
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 9000
  type: NodePort